version: '3'
services:
  backend:
    image: backend-image:backendDocker
    networks:
      - netwerk1
      - default
    depends_on:
      - mysql
    labels:
      - "traefik.http.routers.backend.rule=Host(`s143299.devops-ap.be`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend-service.loadbalancer.server.port=3000"

  frontend:
    image: frontend-image:latest
    networks:
        - netwerk1
    labels:
      - "traefik.http.routers.frontend.rule=Host(`s143299.devops-ap.be`)&& PathPrefix(`/api/`) "
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend.entrypoints=websecure"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "examen"
      MYSQL_USER: "usr"
      MYSQL_PASSWORD: "user_pwd"
    networks:
      - netwerk1
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  netwerk1:
    external: true
    name: traefik

volumes:
  mysql-data:
