version: '3'
services:
  backend:
    image: backend-image:backendDocker
    # Voeg eventuele extra configuratie voor de backend toe, zoals poorten, omgevingsvariabelen, volumes, enz.

  frontend:
    image: frontend-image:latest
    ports:
      - "80:80"

  mysql:
    image: mysql:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - sql-netwerk

volumes:
  mysql_data:

networks:
  sql-netwerk:
    external: true  # Dit betekent dat het netwerk mogelijk elders is gedefinieerd
